import type { SemanticTokens } from '@pandacss/types'

export const semanticColors: SemanticTokens['colors'] = {
    "accent-1": { value: "{colors.purple-1}" },
    "accent-2": { value: "{colors.purple-2}" },
    "accent-3": { value: "{colors.purple-3}" },
    "accent-4": { value: "{colors.purple-4}" },
    "accent-5": { value: "{colors.purple-5}" },
    "accent-6": { value: "{colors.purple-6}" },
    "accent-7": { value: "{colors.purple-7}" },
    "accent-8": { value: "{colors.purple-8}" },
    "accent-9": { value: "{colors.purple-9}" },
    "accent-10": { value: "{colors.purple-10}" },

    // this generates bg-alias.body instead of bg-alias-body
    // "bg-alias": {
    //     body: {value: { base: "{colors.gray}", _dark: "{colors.neutral-10}"}},
    //     surface: {value: { base: "{colors.white}", _dark: "{colors.neutral-9}"}},
    //     "soft-break": {value: { base: "{colors.gray}", _dark: "{colors.neutral-10}"}},
    //     "mid-break": {value: { base: "{colors.neutral-1}", _dark: "{colors.neutral-8}"}},
    //     "hard-break": {value: { base: "{colors.neutral-3}", _dark: "{colors.neutral-6}"}},
    //     basic: {value: { base: "{colors.neutral-8}", _dark: "{colors.neutral-5}"}},
    //     "basic-hover": {value: { base: "{colors.neutral-9}", _dark: "{colors.neutral-6}"}},
    //     "basic-active": {value: { base: "{colors.neutral-10}", _dark: "{colors.neutral-7}"}},
    //     "basic-transparent": {value: { base: "{colors.transparent}", _dark: "{colors.transparent}"}},
    //     "basic-transparent-hover": {value: { base: "{colors.neutral-2}", _dark: "{colors.neutral-7}"}},
    //     "basic-transparent-active": {value: { base: "{colors.neutral-3}", _dark: "{colors.neutral-8}"}},
    //     "static-white": {value: { base: "{colors.white}", _dark: "{colors.white}"}},
    //     "grey-hover": {value: { base: "{colors.neutral-1}", _dark: "{colors.neutral-6}"}},
    //     "grey-active": {value: { base: "{colors.neutral-3}", _dark: "{colors.neutral-7}"}},
    //     "accent": {value: { base: "{colors.purple-6}", _dark: "{colors.purple-6}"}},
    //     "accent-hover": {value: { base: "{colors.purple-8}", _dark: "{colors.purple-8}"}},
    //     "accent-active": {value: { base: "{colors.purple-9}", _dark: "{colors.purple-9}"}},
    //     "accent-faint": {value: { base: "{colors.purple-1}", _dark: "{colors.purple-9}"}},
    //     "accent-light": {value: { base: "{colors.purple-2}", _dark: "{colors.purple-8}"}},
    //     "accent-transparent": {value: { base: "{colors.transparent}", _dark: "{colors.transparent}"}},
    //     "accent-transparent-hover": {value: { base: "{colors.purple-1}", _dark: "{colors.purple-9}"}},
    //     "accent-transparent-active": {value: { base: "{colors.purple-2}", _dark: "{colors.purple-9}"}},
    //     "alert": {value: { base: "{colors.alert-6}", _dark: "{colors.alert-6}"}},
    //     "alert-hover": {value: { base: "{colors.alert-8}", _dark: "{colors.alert-8}"}},
    //     "alert-active": {value: { base: "{colors.alert-9}", _dark: "{colors.alert-9}"}},
    //     "alert-faint": {value: { base: "{colors.alert-1}", _dark: "{colors.alert-9}"}},
    //     "alert-light": {value: { base: "{colors.alert-2}", _dark: "{colors.alert-8}"}},
    //     "alert-transparent": {value: { base: "{colors.transparent}", _dark: "{colors.transparent}"}},
    //     "alert-transparent-hover": {value: { base: "{colors.alert-1}", _dark: "{colors.alert-8}"}},
    //     "alert-transparent-active": {value: { base: "{colors.alert-2}", _dark: "{colors.alert-9}"}},
    //     "warning": {value: { base: "{colors.warning-3}", _dark: "{colors.warning-3}"}},
    // }
            // "light-bg-alias-warning-hover": "$warning-8",
            // "light-bg-alias-warning-active": "$warning-9",
            // "light-bg-alias-warning-faint": "$warning-1",
            // "light-bg-alias-warning-light": "$warning-2",
            // "light-bg-alias-success": "$success-6",
            // "light-bg-alias-success-hover": "$success-8",
            // "light-bg-alias-success-active": "$success-9",
            // "light-bg-alias-success-faint": "$success-1",
            // "light-bg-alias-success-light": "$success-2",
            // "light-bg-alias-transparent": "transparent",
            // "light-bg-alias-input-selection": "$accent-3",
            // "light-bg-alias-underlay": "rgba(31, 33, 81, 0.5)",


            // "dark-bg-alias-warning-hover": "$warning-8",
            // "dark-bg-alias-warning-active": "$warning-9",
            // "dark-bg-alias-warning-faint": "$warning-8",
            // "dark-bg-alias-warning-light": "$warning-7",
            // "dark-bg-alias-success": "$success-6",
            // "dark-bg-alias-success-hover": "$success-8",
            // "dark-bg-alias-success-active": "$success-9",
            // "dark-bg-alias-success-faint": "$success-9",
            // "dark-bg-alias-success-light": "$success-8",
            // "dark-bg-alias-transparent": "transparent",
            // "dark-bg-alias-input-selection": "$accent-5",
            // "dark-bg-alias-underlay": "rgba(31, 33, 81, 0.5)",

        "bg-alias-body": {value: { base: "{colors.gray}", _dark: "{colors.neutral-10}"}},
        "bg-alias-surface": {value: { base: "{colors.white}", _dark: "{colors.neutral-9}"}},
        "bg-alias-soft-break": {value: { base: "{colors.gray}", _dark: "{colors.neutral-10}"}},
        "bg-alias-mid-break": {value: { base: "{colors.neutral-1}", _dark: "{colors.neutral-8}"}},
        "bg-alias-hard-break": {value: { base: "{colors.neutral-3}", _dark: "{colors.neutral-6}"}},
        "bg-alias-basic": {value: { base: "{colors.neutral-8}", _dark: "{colors.neutral-5}"}},
        "bg-alias-basic-hover": {value: { base: "{colors.neutral-9}", _dark: "{colors.neutral-6}"}},
        "bg-alias-basic-active": {value: { base: "{colors.neutral-10}", _dark: "{colors.neutral-7}"}},
        "bg-alias-basic-transparent": {value: { base: "{colors.transparent}", _dark: "{colors.transparent}"}},
        "bg-alias-basic-transparent-hover": {value: { base: "{colors.neutral-2}", _dark: "{colors.neutral-7}"}},
        "bg-alias-basic-transparent-active": {value: { base: "{colors.neutral-3}", _dark: "{colors.neutral-8}"}},
        "bg-alias-static-white": {value: { base: "{colors.white}", _dark: "{colors.white}"}},
        "bg-alias-grey-hover": {value: { base: "{colors.neutral-1}", _dark: "{colors.neutral-6}"}},
        "bg-alias-grey-active": {value: { base: "{colors.neutral-3}", _dark: "{colors.neutral-7}"}},
        "bg-alias-accent": {value: { base: "{colors.purple-6}", _dark: "{colors.purple-6}"}},
        "bg-alias-accent-hover": {value: { base: "{colors.purple-8}", _dark: "{colors.purple-8}"}},
        "bg-alias-accent-active": {value: { base: "{colors.purple-9}", _dark: "{colors.purple-9}"}},
        "bg-alias-accent-faint": {value: { base: "{colors.purple-1}", _dark: "{colors.purple-9}"}},
        "bg-alias-accent-light": {value: { base: "{colors.purple-2}", _dark: "{colors.purple-8}"}},
        "bg-alias-accent-transparent": {value: { base: "{colors.transparent}", _dark: "{colors.transparent}"}},
        "bg-alias-accent-transparent-hover": {value: { base: "{colors.purple-1}", _dark: "{colors.purple-9}"}},
        "bg-alias-accent-transparent-active": {value: { base: "{colors.purple-2}", _dark: "{colors.purple-9}"}},
        "bg-alias-alert": {value: { base: "{colors.alert-6}", _dark: "{colors.alert-6}"}},
        "bg-alias-alert-hover": {value: { base: "{colors.alert-8}", _dark: "{colors.alert-8}"}},
        "bg-alias-alert-active": {value: { base: "{colors.alert-9}", _dark: "{colors.alert-9}"}},
        "bg-alias-alert-faint": {value: { base: "{colors.alert-1}", _dark: "{colors.alert-9}"}},
        "bg-alias-alert-light": {value: { base: "{colors.alert-2}", _dark: "{colors.alert-8}"}},
        "bg-alias-alert-transparent": {value: { base: "{colors.transparent}", _dark: "{colors.transparent}"}},
        "bg-alias-alert-transparent-hover": {value: { base: "{colors.alert-1}", _dark: "{colors.alert-8}"}},
        "bg-alias-alert-transparent-active": {value: { base: "{colors.alert-2}", _dark: "{colors.alert-9}"}},
        "bg-alias-warning": {value: { base: "{colors.warning-3}", _dark: "{colors.warning-3}"}},


}